# Generated by Django 4.1.7 on 2023-05-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter_media',
            name='advertisementQR',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
