# Generated by Django 4.1.7 on 2023-06-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_content_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='test',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.CharField(default='', max_length=30),
        ),
    ]
