# Generated by Django 4.1.7 on 2023-06-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_content_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='test',
        ),
    ]
