# Generated by Django 4.1.7 on 2023-06-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_remove_content_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='test',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='phonenum',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
