# Generated by Django 4.1.7 on 2023-06-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_content_test_alter_content_phonenum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='test',
        ),
    ]
