# Generated by Django 4.1.3 on 2022-12-08 16:05

import Authentication.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='여기에 입력 하시오.', max_length=50, null=True)),
                ('user_description', models.TextField(blank=True, default='여기에 입력 하시오.', max_length=500, null=True)),
                ('user_profile', models.FileField(blank=True, null=True, upload_to=Authentication.models.profile_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('user_auth', models.CharField(choices=[('최고관리자', 'Super_Admin'), ('쉘터관리자', 'Shelter_Admin')], default=0, max_length=200, null=True)),
                ('user_status', models.CharField(choices=[('활성화', 'ACTIVATE'), ('탈퇴', 'STOPED'), ('대기', 'PAUSED'), ('정지', 'BANNED')], default='대기', max_length=20, null=True)),
                ('user', models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
